name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: athenna
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_ROOT_PASSWORD: root
        ports:
          - '5432:5432'
    strategy:
      matrix:
        node-version:
          - 21.x
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: node artisan migration:run --env test --connection postgres

      - name: Run seeders
        run: node artisan db:seed --env test --connection postgres

      - name: Run tests
        run: npm run test:coverage

      - name: Test code compilation
        run: npm run build
